[package]
name = "myTerm"
version = "0.1.0"
edition = "2021"

# default-run 
# Runs myTerm when not specified
default-run = "myTerm"

[dependencies]
speedy2d = "1.0"
nix = { version = "0.29", default-features = false, features = ["term", "process", "fs"] }
